import { ExperienceItem } from '@/types';

export const experiences: ExperienceItem[] = [
  {
    id: 1,
    title: 'Software Developer, Intern',
    company: 'IST Networks',
    location: 'Cairo, Egypt',
    duration: 'Jul 2025 - Aug 2025',
    description:
      'Contributing to both Web and App Development teams within a leading Customer Experience (CX) tech company, delivering scalable and integrated solutions.',
    responsibilities: [
      'Worked in the Web Development team using React and ASP.NET (MVC architecture) within a monorepo structure',
      'Tested and validated APIs using Postman',
      'Deployed web modules via GitHub Pages',
      'Collaborated with the App Development team leveraging Spring Boot for backend services and Cisco Call Studio for IVR integrations',
      'Engaged in end-to-end SDLC phases under both Waterfall and Agile methodologies',
      'Managed tasks and workflow using Trello',
      'Developed presentation skills and deepened understanding of SDLC, Waterfall, and Agile frameworks',
    ],
    skills: ['React', 'ASP.NET (MVC)', 'Spring Boot', 'Cisco Call Studio (IVR)', 'API testing (Postman)', 'SDLC'],
    tools: ['VS Code', 'Visual Studio', 'GitHub Pages', 'Postman', 'Trello'],
  },
  {
    id: 2,
    title: 'Full Stack Engineer, Intern',
    company: 'T.E.C Tawreed',
    location: 'Cairo, Egypt',
    duration: 'Sep 2024 – Oct 2024',
    description:
      'Contributed to T.E.C Tawreed’s B2B e-procurement platform, building production-grade features with a strong focus on clean architecture, validation, and team workflows.',
    responsibilities: [
      'Applied OOP and single-responsibility principles across both backend classes and frontend components for maintainable and scalable code',
      'Learned and actively worked with ESLint, Prettier, and Husky to maintain a clean and consistent codebase',
      'Created initial UI sketches in Figma and implemented responsive frontends with Next.js and TypeScript',
      'Validated user inputs on the frontend using Yup and ensured data integrity at the backend level',
      'Used TypeORM to work with PostgreSQL entities and updated database models as needed',
      'Validated backend environment files (.env) and static configuration files to ensure correctness and security',
      'Collaborated with the team through Git/GitHub, practicing proper branching, commits, and pull requests',
    ],
    skills: [
      'Next.js',
      'React',
      'TypeScript',
      'Node.js',
      'PostgreSQL',
      'TypeORM',
      'OOP',
      'Component Architecture',
      'Yup',
      'API Design',
      'Git/GitHub',
    ],
    tools: ['Cursor', 'Postman', 'DBeaver', 'Figma', 'shadcn/ui', 'ESLint', 'Prettier', 'Husky'],
  },
  {
    id: 3,
    title: 'Full Stack Developer, Intern',
    company: 'Neuronitex',
    location: 'Remote',
    duration: 'Aug 2024 - Sep 2024',
    description:
      'Developed real-world web applications using the MERN stack while contributing to both front-end and back-end systems.',
    responsibilities: [
      'Built RESTful APIs with Express.js',
      'Implemented WebSocket communication using Socket.io',
      'Managed front-end and back-end logic',
      'Optimized user authentication and responsive design',
    ],
    skills: ['MongoDB', 'Express.js', 'React', 'Node.js', 'Socket.io'],
    tools: ['VS Code', 'Postman', 'MongoDB Atlas', 'Git', 'Vercel'],
  },
  {
    id: 4,
    title: 'Technical Courses',
    company: 'Self-Directed Learning & Professional Academies',
    location: 'Online',
    duration: '2022 - Present',
    description:
      'Completed technical training programs covering advanced database engineering, backend systems architecture, full-stack web development, and competitive programming. These intensive courses provided deep theoretical knowledge and hands-on practical experience across multiple domains of software engineering.',
    responsibilities: [
      'Fundamentals of Database Engineering by Hussein Nasser: mastered advanced database internals including storage engines, B-Trees and indexing strategies, transaction management with ACID properties, database partitioning, replication techniques, and query optimization. Gained deep understanding of how databases work under the hood, connection pooling, and performance tuning for high-traffic applications.',
      'Fundamentals of Backend Engineering by Hussein Nasser: developed expertise in backend system architecture, learning modern communication protocols (HTTP/1.1-3, gRPC, WebRTC, WebSockets, QUIC), network fundamentals including TCP/UDP, TLS encryption and security protocols, operating system concepts for servers, connection handling patterns, execution models, and scalable system design principles.',
      'Docker and Kubernetes by Big Data بالعربي (10+ Hours): completed in-depth containerization training covering container architecture fundamentals, Docker Engine deep dive, image creation and management, container networking and storage, Dockerfile optimization, Docker Compose for multi-container applications, Docker Swarm orchestration, Docker Stack deployment, container registries, and Kubernetes architecture. Advanced topics included K8s logical architecture, deployments, Minikube setup, and practical containerized application development.',
      'SEF Academy Full-Stack Development Course: built complete full-stack web applications using the MERN stack (MongoDB, Express.js, React, Node.js), focusing on RESTful API development, database schema design, user authentication and authorization, responsive frontend interfaces with Bootstrap, state management in React, and deployment strategies. Completed multiple real-world projects demonstrating end-to-end development skills.',
      'Coach Academy Competitive Programming Course (Level 1 & 2): achieved proficiency in algorithmic problem-solving through intensive training in data structures (arrays, linked lists, trees, graphs), advanced algorithms including graph traversal (DFS, BFS), shortest path algorithms, dynamic programming for optimization problems, number theory concepts like modular arithmetic and binary exponentiation, and complex mathematical problem-solving techniques.',
    ],
    skills: [
      'Database Engineering',
      'MongoDB',
      'Backend Architecture',
      'Node.js',
      'Express.js',
      'React.js',
      'JavaScript',
      'RESTful APIs',
      'HTTP Protocols',
      'WebSockets',
      'Docker',
      'Kubernetes',
      'Containerization',
      'Algorithms & Data Structures',
      'Dynamic Programming',
      'Graph Theory',
      'System Design',
      'Performance Optimization',
      'Network Security',
      'Competitive Programming',
      'Full-Stack Development',
    ],
    tools: [
      'VS Code',
      'MongoDB Atlas',
      'Postman',
      'Git & GitHub',
      'Vercel',
      'Socket.io',
      'Docker',
      'Docker Compose',
      'Docker Swarm',
      'Kubernetes',
      'Minikube',
      'Chrome DevTools',
      'Codeforces',
      'LeetCode',
      'Bootstrap',
      'React DevTools',
    ],
  },
];
